version: "3.8"

x-default-container: &default-container
  environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Berlin
  restart: unless-stopped

services:
  traefik:
    container_name: traefik
    image: traefik
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.defaultRule=HostRegexp(`^{{ .ContainerName }}.*$`)"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=jonasgrosch96@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.entrypoints=web"
      - "traefik.http.services.admin.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`traefik.lan`)"
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:172.17.0.1
    networks:
      traefik-network:
        ipv4_address: 172.16.0.2
      stream-network:
        ipv4_address: 172.16.1.2
      arrs-network:
        ipv4_address: 172.16.2.2

  adguard:
    <<: *default-container
    container_name: adguard
    image: adguard/adguardhome
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.lan`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=5353"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 5353:80/tcp
      - 5354:443/tcp
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      traefik-network:
        ipv4_address: 172.16.0.3

  homeassistant:
    <<: *default-container
    container_name: homeassistant
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.lan`) || Host(`home.grosch.io`)"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant.tls.certresolver=myresolver"
      - "traefik.http.routers.homeassistant.tls.domains[0].main=home.grosch.io"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host
    # (No Docker network needed for host mode)

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - /opt/matter-server:/data
      - /run/dbus:/run/dbus:ro
    network_mode: host
    # (No Docker network needed for host mode)

  whisper:
    <<: *default-container
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model tiny-int8 --language en
    volumes:
      - /opt/whisper-data:/data
    restart: unless-stopped
    network_mode: host

  piper:
    <<: *default-container
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice en_US-lessac-medium
    volumes:
      - /opt/piper-data:/data
    restart: unless-stopped
    network_mode: host

volumes:
  adguard_work:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/adguard/work"

  adguard_conf:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/adguard/conf"

  homeassistant_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/homeassistant"

networks:
  # Network 1: for Traefik and services in this file
  traefik-network:
    name: traefik-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1

  # Network 2: for Jellyfin/Plex
  stream-network:
    name: stream-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1

  # Network 3: for sabnzbd, radarr, sonarr, etc.
  arrs-network:
    name: arrs-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24
          gateway: 172.16.2.1