version: "3.8"

# Setup-Standards
x-default-container: &default-container
  environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Berlin
  restart: unless-stopped

# Media access for media containers
x-mediarr-container: &mediarr-container
  <<: *default-container
  network_mode: service:tailscale
  depends_on:
    - tailscale

services:
  tailscale:
    <<: *default-container
    container_name: tailscale
    image: tailscale/tailscale:latest
    environment:
      - TS_EXTRA_ARGS=--accept-routes --advertise-routes=192.168.178.0/24 --exit-node=100.76.46.72 --exit-node-allow-lan-access
      - TS_HOSTNAME=mediarr
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=true
      - TS_USERSPACE=false
    volumes:
      - tailscale_state:/var/lib/tailscale
      - /lib/modules:/lib/modules            # host bind (needed for kernel modules)
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    sysctls:
      - net.ipv4.conf.eth0.rp_filter=2
    ports:
      - 53333:53333/udp # Wireguard server Port
      - 32222:32222     # Wireguard sidecar Port
      - 8081:8080       # sabnzbd
      - 6767:6767       # bazarr
      - 5055:5055       # jellyseerr
      - 9696:9696       # prowlarr
      - 7878:7878       # radarr
      - 8989:8989       # sonarr

  sabnzbd:
    <<: *mediarr-container
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.lan`)"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
    volumes:
      - sabnzbd_config:/config
      - downloads:/mnt/downloads

  bazarr: 
    <<: *mediarr-container
    image: linuxserver/bazarr 
    container_name: bazarr 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.lan`)"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    volumes: 
      - bazarr_config:/config 
    depends_on:
      - tailscale
      - sonarr 
      - radarr 

  jellyseerr: 
    <<: *mediarr-container
    image: fallenbagel/jellyseerr
    container_name: jellyseerr 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.lan`)"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
    volumes: 
      - jellyseerr_config:/app/config
    depends_on: 
      - tailscale
      - sonarr 
      - radarr

  prowlarr: 
    <<: *mediarr-container
    image: linuxserver/prowlarr 
    container_name: prowlarr 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.lan`)"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    volumes: 
      - prowlarr_config:/config 

  radarr: 
    <<: *mediarr-container
    image: linuxserver/radarr 
    container_name: radarr 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.lan`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    volumes: 
      - radarr_config:/config
      - media:/mnt/media 
      - downloads:/mnt/downloads 
    depends_on: 
      - tailscale
      - prowlarr 

  sonarr: 
    <<: *mediarr-container
    image: lscr.io/linuxserver/sonarr:latest 
    container_name: sonarr 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.lan`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    volumes: 
      - sonarr_config:/config
      - media:/mnt/media 
      - downloads:/mnt/downloads 
    depends_on: 
      - tailscale
      - prowlarr 

volumes:
  media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/media"
  
  downloads:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/downloads"

  # ------------------------------------------------
  # PER-SERVICE CONFIG VOLUMES
  # ------------------------------------------------

  tailscale_state:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/tailscale/state"

  sabnzbd_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/sabnzbd/config"

  bazarr_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/mediarr/bazarr"

  jellyseerr_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/mediarr/jellyseerr"

  prowlarr_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/mediarr/prowlarr"

  radarr_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/mediarr/radarr"

  sonarr_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/mediarr/sonarr"