version: "3.8"

# Setup-Standards
x-default-container: &default-container
  environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Berlin
  restart: unless-stopped

services:
  jellyfin:
    <<: *default-container
    container_name: jellyfin 
    image: jellyfin/jellyfin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.lan`) || Host(`jellyfin.home.grosch.io`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.routers.jellyfin.tls.domains[0].main=jellyfin.home.grosch.io"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    volumes: 
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - media:/mnt/media 
    devices: 
      - /dev/dri/renderD128:/dev/dri/renderD128

  plex:
    <<: *default-container
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
    volumes:
      - plex_config:/config
      - media:/mnt/media 

volumes:
  media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/media"

  # ------------------------------------------------
  # PER-SERVICE CONFIG VOLUMES
  # ------------------------------------------------
  jellyfin_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/jellyfin/config"
  jellyfin_cache:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/jellyfin/cache"

  plex_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.74,nolock,soft,rw"
      device: ":/var/nfs/shared/configs/plex"

  